config/routes.rb
SampleApp::Application.routes.draw do
resources :users

root to: 'static_pages#home'

match '/signup', to: 'users#new'

match '/help',    to: 'static_pages#help'
match '/about',   to: 'static_pages#about'
match '/contact', to: 'static_pages#contact' 

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessible :name, :email, :password, :password_confirmation
has_secure_password

before_save { |user| user.email = user.email.downcase}

validates :name,  presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[\w+\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					uniqueness: { case_sensitive: false }
validates :password, length: { minimum: 6 }
validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end


  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
	def show
		@user = User.find(params[:id])
  end
	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:success] = "Welcome to the Sample App"
			redirect_to @user
		else
		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title)
		base_title ='Titolo Sample App'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://www.corriere.it">corriere on line</a>
		by RCS
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://news.railstotorial.org"></a>News</li>
		</ul>	
	</nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", root_path, id: "logo" %>
			<nav> 
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
<header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"</script>
  	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title))%></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <%= render 'layouts/shim'%>
	</head>
	<body>
		<%= render 'layouts/header'%>
		<div class="container">
			<% flash.each do |key,value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
				<%= render 'layouts/footer'%>
				<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title , 'About us') %>
<h1>About us</h1>

<p>
	This is the home page for
	<a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
	sample application
</p>

app/views/static_pages/contact.html.erb
<% provide(:title , 'Contact') %>

<h1>Contact</h1>

<p>
	This is the home page for
	<a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
	sample application
</p>

app/views/static_pages/help.html.erb
<% provide(:title , 'Help') %>

<h1>Help</h1>

<p>
	This is the home page for
	<a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
	sample application
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>
	<p>
		This is the home page for
		<a href="http://railstutorial.org">Ruby on Rails Tutorial</a>
		sample application
	</p>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>